config/routes.rb
Rails.application.routes.draw do
  root to: 'customers/dashboards#show'

#devise routes -----------------------------------------------------------------

  devise_for :customers,
    controllers: { invitations: "customers/invitations"}

  devise_for :employees,
    controllers: { omniauth_callbacks: "employees/omniauth_callbacks"}



#employee routes --------------------------------------------------------------

  namespace :employees do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :helpdesk_tickets

    ## !! MFR 30-Aug-2016
    # routes added for consulting hours because it's related
    # to customer
    # /employees/customers/:customer_id/consulting_hours...
    resources :customers, only: [:index, :show] do |variable|
      resources :consulting_hours
    end
    ## !!

    # /projects (bla)
    # /projects/:id # listing the phases
    resources :projects, except: [:destroy] do
      # /projects/:project_id/phases/new + create
      # /projects/:project_id/phases/:id # listing lots
      resources :phases do
      end

      resources :news, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :lots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :buildings, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :storage_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :parking_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        #resources :consulting_hours
        resources :documents
        resources :decisions
        resources :handovers
        resources :informations
        resources :site_visits
        resources :payments
        resources :pictures
      end
    end
  end

  #customer routes -------------------------------------------------------------

  namespace :customers do

    root to: 'customers/dashboards#show'
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update]

    resources :units, only: [:show, :index] do
      resource :dashboard,  only: [:show]

      resources :news,      only: [:index, :show]

      resources :decisions, only: [:index, :show] do
        member do
          patch :approve
          patch :reject
        end
      end

      resources :site_visits,   only: [:index, :show]
      resources :handovers,     only: [:index, :edit, :update] # for the remarks
      resources :payments,      only: [:index, :show]
      resources :documents,     only: [:index]
      resources :pictures,      only: [:index, :show]

      resources :informations, only: [:index, :show] do
        member do
          patch :read
        end
      end

      resources :parking_units, only: [:show, :index]
      resources :storage_units, only: [:show, :index]

      resources :helpdesk_tickets, only: [:show, :index, :new, :create]
      # resources :suppliers TODO
    end
  end
end

app/controllers/employees/base_controller.rb
class Employees::BaseController < ApplicationController
  before_action :set_project, if: :employee_signed_in?
  before_action :set_unit_employee, if: :employee_signed_in?
  before_action :authenticate_employee!
  layout "employee"

  ###################################################################

  private

    def set_project #------------------------------------------------
      # @project will be nil if the current employee is not attached
      # to any project
      @project = nil
      unless current_employee.projects.nil? || current_employee.projects.empty?
        if params[:project_id]
          projects = current_employee.projects
          projects.each do |project|
            if project.id == params[:project_id]
              @project = project if @project.nil?
            end
          end
        else
          @project = current_employee.projects.first
        end
      end
    end

  def set_unit_employee #--------------------------------------------
    # @unit will be nil if there's no unit related to the current
    # employee
    @unit = nil
    unless current_employee.projects.nil? || current_employee.projects.empty?
      if params[:unit_id] # if there is a current unit
        un = Unit.find(params[:unit_id])
        emp = un.building.lot.phase.project.employees.first
        @unit = un if emp == current_employee
      end
    end
  end

  def set_current_phase_id(phase)  #---------------------------------
    # keeps track of the current phase since
    # phase_id does not appear in all routes
    # to lots
    session[:current_phase_id] = phase.id
  end

  def get_current_phase_id
    return session[:current_phase_id]
  end

  def set_current_lot_id(lot) #--------------------------------------
    # keeps track of the current lot since
    # lot_id does not appear in all routes
    # to buildings
    session[:current_lot_id] = lot.id
  end

  def get_current_lot_id
    return session[:current_lot_id]
  end

  def set_current_building_id(building) #----------------------------
    # keeps track of the current lot since
    # lot_id does not appear in all routes
    # to buildings
    session[:current_building_id] = building.id
  end

  def get_current_building_id
    return session[:current_building_id]
  end

  def set_current_unit_id(unit) #------------------------------------
    # keeps track of the current lot since
    # lot_id does not appear in all routes
    # to buildings
    session[:current_unit_id] = unit.id
  end

  def get_current_unit_id
    return session[:current_unit_id]
  end

end

app/controllers/employees/buildings_controller.rb
class Employees::BuildingsController < Employees::BaseController

  before_action :set_init, except: [:destroy]

  def index
    @buildings = @lot.buildings
  end

  def show
    @building = @lot.buildings.find(params[:id])
    set_current_building_id(@building)
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(params_building)
    @building.lot_id = @lot.id
    if @building.save
      redirect_to employees_project_building_path(@project.id, @building)
    else
      render :new
    end
  end

  def edit
    @building = @lot.buildings.find(params[:id])
  end

  def update
    @building = @lot.buildings.find(params[:id])
    if @building.update(params_building)
      redirect_to employees_project_building_path(@project.id, @building)
    else
      render :edit
    end
  end

  def save_phase(phase)
    set_current_phase_id(phase)
  end
  helper_method :save_phase

private ##################################################################

  def set_init
    @project = current_employee.projects.find(params[:project_id])
    @phase = @project.phases.find(get_current_phase_id)
    @lot = @phase.lots.find(get_current_lot_id)
  end

  def params_building
    params.fetch(:building, {}).permit(:lot_id, :building_name,
                                       :description, :address,
                                       :floors, :shared_space,
                                       :elevator_amount,
                                       :picture, :picture_cache)
  end

end

app/controllers/employees/consulting_hours_controller.rb
class Employees::ConsultingHoursController < Employees::BaseController

  before_action :set_init, except: [:destroy]

  def index #--------------------------------------------------------
    # how many hours is the client entitled to ?
    @units = Unit.where("customer_id = " + params[:customer_id])
    @consulting_quota = 0
    @units.each do |unit|
      if unit.consulting_hours.nil? || unit.consulting_hours == 0 # if consulting_hours is not
        @consulting_quota += Unit.DEFAULT_CONSULTING_HOURS        # set, we use the default value
      else                                                        # specified in the Unit model.
        @consulting_quota += unit.consulting_hours
      end
    end

    # how many hours have been used ?
    @chs = ConsultingHour.where("customer_id = " + params[:customer_id])
    @used_hours = 0
    @chs.each do |ch|
      @used_hours += ch.elapsed_time
    end

  end

  def show #---------------------------------------------------------
    # not implemented, too little to show for a dedicated form.
  end

  def new #----------------------------------------------------------
    @ch = ConsultingHour.new
  end

  def create #-------------------------------------------------------
    @ch = ConsultingHour.new(params_ch)
    @ch.customer_id = @customer.id
    @ch.employee_id = @current_employee.id
    if @ch.save
      redirect_to employees_customer_consulting_hours_path(@customer.id)
    else
      render :new
    end
  end

  def edit #---------------------------------------------------------
    @ch = @customer.consulting_hours.find(params[:id])
  end

  def update #-------------------------------------------------------
    @ch = @customer.consulting_hours.find(params[:id])
    if @ch.update(params_ch)
      redirect_to employees_customer_consulting_hours_path(@customer.id)
    else
      render :edit
    end

  end

  def destroy #------------------------------------------------------

  end

private ##################################################################

  def set_init
    @customer = Customer.find(params[:customer_id])
  end

  def params_ch
    params.fetch(:consulting_hour, {}).permit(:elapsed_time, :customer_id,
                                               :employee_id, :description,
                                               :date)
  end

end

app/controllers/employees/customers_controller.rb
class Employees::CustomersController< Employees::BaseController

  def index
    @customers = Customer.all.order(last_name: :asc)
  end

  def show
    @customer = Customer.find(params[:id])
    @units = Unit.where("customer_id = " + params[:id])
  end

end

app/controllers/employees/dashboards_controller.rb
class Employees::DashboardsController < Employees::BaseController
  def show
    @employee_projects = current_employee.projects


  end
end

app/controllers/employees/decisions_controller.rb
class Employees::DecisionsController < Employees::BaseController
    def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/employees/documents_controller.rb
class Employees::DocumentsController < Employees::BaseController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/employees/handovers_controller.rb
class Employees::HandoversController < Employees::BaseController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/employees/helpdesk_tickets_controller.rb
class Employees::HelpdeskTicketsController < Employees::BaseController

  def index#--------------------------------------------------------
    @tickets = HelpdeskTicket.where(employee_id:current_employee.id)
  end

  def show #--------------------------------------------------------
    @ticket = HelpdeskTicket.find(params[:id])
  end


  def edit #--------------------------------------------------------
    @ticket = HelpdeskTicket.find(params[:id])
    respond_to do |format|
      format.html { redirect_to edit_employees_helpdesk_ticket_path(@ticket.id) }
      format.js
    end
  end


  def update #--------------------------------------------------------
    @ticket = HelpdeskTicket.find(params[:id])
    if @ticket.update(params_helpdesk_ticket)
      redirect_to employees_helpdesk_tickets_path and return
    else
      render :edit
    end
  end



end



private

  def params_helpdesk_ticket
    params.fetch(:helpdesk_ticket, {}).permit(:title, :description, :answers, :status)
  end

app/controllers/employees/informations_controller.rb
class Employees::InformationsController < Employees::BaseController

    def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/employees/lots_controller.rb
class Employees::LotsController < Employees::BaseController

  before_action :set_init, except: [:destroy]

  def index #--------------------------------------------------------
    @lots = @phase.lots
  end

  def show #---------------------------------------------------------
    @lot = @phase.lots.find(params[:id])
    set_current_lot_id(@lot)
  end

  def new #----------------------------------------------------------
    @lot = Lot.new
    respond_to do |format|
      format.html { redirect_to employees_project_lots_path }
      format.js
    end
  end

  def create #--------------------------------------------------------
    @lot = Lot.new(params_lot)
    @lot.phase_id = @phase.id
    if @lot.save
      redirect_to employees_project_lot_path(@project.id, @lot)
    else
      render :new
    end
  end

  def edit #---------------------------------------------------------
    @lot = @phase.lots.find(params[:id])
  end

  def update #-------------------------------------------------------
    @lot = @phase.lots.find(params[:id])
    if @lot.update(params_lot)
      redirect_to employees_project_lot_path(@project.id, @lot)
    else
      render :edit
    end
  end


  def save_phase(phase)
    set_current_phase_id(phase)
  end
  helper_method :save_phase

private ##################################################################

  def set_init
    @project = current_employee.projects.find(params[:project_id])
    @phase = @project.phases.find(get_current_phase_id)
  end

  def params_lot
    params.fetch(:lot, {}).permit(:phase_id, :lot_number,
                                  :description, :cadastral_reference,
                                  :lot_size, :picture, :picture_cache)
  end

end

app/controllers/employees/news_controller.rb
class Employees::NewsController < Employees::BaseController

  before_action :set_init, except: [:destroy]

  def index #--------------------------------------------------------
    @news= News.where(phase_id: @phase)
  end

  def show #---------------------------------------------------------
    @news = @phase.news.find(params[:id])
  end

  def new #----------------------------------------------------------
     @news = News.new
  end

  def create #-------------------------------------------------------
    @news = News.new(params_news)
    @news.phase_id = @phase.id
    if @news.save
      redirect_to employees_project_news_path(@project.id, @news)
    else
      render :new
    end
  end

  def edit #---------------------------------------------------------
    @news = @phase.news.find(params[:id])
  end

  def update #-------------------------------------------------------
    @news = @phase.news.find(params[:id])
    if @news.update(params_news)
      redirect_to employees_project_news_path(@project.id, @news)
    else
      render :edit
    end
  end

  def destroy #------------------------------------------------------
  end


  private ###########################################################

  def set_init
    @project = current_employee.projects.find(params[:project_id])
    @phase = @project.phases.find(get_current_phase_id)
  end

  def params_news
    params.fetch(:news, {}).permit(:phase_id, :title,
                                   :description, :date,
                                   :picture, :picture_cache)
  end
end

app/controllers/employees/omniauth_callbacks_controller.rb
class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @employee = Employee.from_omniauth(request.env["omniauth.auth"])

      if @employee && @employee.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @employee, :event => :authentication
      else
        oauth = request.env["omniauth.auth"].dup
        oauth.delete("extra")

        session["devise.google_data"] = oauth
        redirect_to new_employee_session_url
      end
  end
end

app/controllers/employees/payments_controller.rb
class Employees::PaymentsController < Employees::BaseController
    def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/employees/site_visits_controller.rb
class Employees::SiteVisitsController < Employees::BaseController
    def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/views/employees/phases/_modalcontent_new_phase.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h3 class="modal-title">New Phase</h3>
</div>
<%= simple_form_for(@phase, url: employees_project_phases_path ) do |f| %>
<div class="modal-body">
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :phase_number %>
      <%= f.input :description %>
      <%= f.input :duration %>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden %>
    </div>

</div>

<div class="modal-footer">
  <div class="form-actions">
      <%= f.button :submit %>
      <% end %>
  </div>
</div>

app/views/employees/phases/edit.html.erb
<div>
  <p>
    Employees > Projects <%= @project.commercial_name %> >
    Phases <%= @phase.phase_number %> > Edit
    <hr>
  </p>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-xs-offset-right-1">
      <%= simple_form_for(@phase, url: employees_project_phase_path(@project, @phase) ) do |f| %>

        <%= f.error_notification %>

       <div class="form-inputs">
          <%= f.input :phase_number %>
          <%= f.input :description %>
          <%= f.input :duration %>
          <%= f.input :picture, label: "Replace picture" %>
          <%= f.input :picture_cache, as: :hidden %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
          <%= link_to 'Cancel', employees_project_phase_path(@project, @phase) , class: "btn btn-danger"%>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/employees/phases/index.html.erb
<div>
  <p>
    Employees > Projects <%= @project.commercial_name %> >
    Phases > Index
    <hr>
  </p>
  <hr>
</div>

<div class="container">

  <div class="row">
    <h3>
      Phases <%= link_to "New Phase", new_employees_project_phase_path, remote: true, class: "btn btn-warning"%>
    </h3>
      <% if @phases.nil? || @phases.empty? %>
        <p>There is no phase for this project.</p>
      <% else %>
        <% @phases.each do |phase| %>
          <div class="col-xs-12 col-sm-4">
          <%  %>
            <div class="thumbnail">
              <div class="caption text-center">
                <h3>Phase number <%= phase.phase_number %></h3>
                <p>
                  <%= link_to 'Details', employees_project_phase_path(@project.id, phase.id), class: "btn btn-normal"%>
                </p>
              </div>
            </div>

          </div>
      <% end %>

    </div>
  <% end %>
  <%= link_to "Back", employees_dashboard_path, class: "btn btn-normal" %>


</div>

<!-- Modal -->
<div class="modal fade" id="newphaseModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/employees/phases/new.html.erb
<div>
  <p>
    Employees > Projects <%= @project.commercial_name %> >
    Phases > New
    <hr>
  </p>
  <hr>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-xs-offset-right-1">
      <%= simple_form_for(@phase, url: employees_project_phases_path ) do |f| %>

        <%= f.error_notification %>

       <div class="form-inputs">
          <%= f.input :phase_number %>
          <%= f.input :description %>
          <%= f.input :duration %>
          <%= f.input :picture %>
          <%= f.input :picture_cache, as: :hidden %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
          <%= link_to 'Cancel',  employees_project_phases_path, class: "btn btn-danger" %>

        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/employees/phases/new.js.erb
$('#newphaseModal .modal-content').html("<%= j render 'modalcontent_new_phase' %>");
$('#newphaseModal').modal('show');

app/views/employees/phases/show.html.erb
<div>
  <p>
    Employees > Projects <%= @project.commercial_name %> >
    Phases <%= @phase.phase_number %> > Show
    <hr>
  </p>
  <hr>
</div>

<div class="container">

  <div class="row">
    <h3>
      Phase number: <%= @phase.phase_number %> <%= link_to "Edit", edit_employees_project_phase_path(@phase.project_id, @phase), class: "btn btn-danger" %>
    </h3>

          <div class="col-xs-12 col-sm-4">
            <div class="thumbnail">
              <div class="caption text-center">
                <p>
                  <strong>Description: </strong><%= @phase.description %>
                </p>
                <p>
                 <strong>Duration: </strong><%= @phase.duration %> weeks
                </p>
                <p>
                  <%= link_to "Lots", employees_project_lots_path(@phase.project_id), class: "btn btn-normal" %>
                  <%= link_to "News", employees_project_news_index_path(@phase.project_id), class: "btn btn-normal" %>
                  </p>

              </div>
            </div>

          </div>
    </div>
        <p>

        <%= link_to "Back", employees_project_phases_path, class: "btn btn-normal" %>
      </p>

</div>