config/routes.rb
Rails.application.routes.draw do
  root to: 'customers/dashboards#show'

#devise routes -----------------------------------------------------------------

  devise_for :customers,
    controllers: { invitations: "customers/invitations"}

  devise_for :employees,
    controllers: { omniauth_callbacks: "employees/omniauth_callbacks"}



#employee routes --------------------------------------------------------------

  namespace :employees do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :helpdesk_tickets

    ## !! MFR 30-Aug-2016
    # routes added for consulting hours because it's related
    # to customer
    # /employees/customers/:customer_id/consulting_hours...
    resources :customers, only: [:index, :show] do |variable|
      resources :consulting_hours
    end
    ## !!

    # /projects (bla)
    # /projects/:id # listing the phases
    resources :projects, except: [:destroy] do
      # /projects/:project_id/phases/new + create
      # /projects/:project_id/phases/:id # listing lots
      resources :phases do
      end

      resources :news, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :lots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :buildings, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :storage_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :parking_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        #resources :consulting_hours
        resources :documents
        resources :decisions
        resources :handovers
        resources :informations
        resources :site_visits
        resources :payments
        resources :pictures
      end
    end
  end

  #customer routes -------------------------------------------------------------

  namespace :customers do

    root to: 'customers/dashboards#show'
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update]

    resources :units, only: [:show, :index] do
      resource :dashboard,  only: [:show]

      resources :news,      only: [:index, :show]

      resources :decisions, only: [:index, :show] do
        member do
          patch :approve
          patch :reject
        end
      end

      resources :site_visits,   only: [:index, :show]
      resources :handovers,     only: [:index, :edit, :update] # for the remarks
      resources :payments,      only: [:index, :show]
      resources :documents,     only: [:index]
      resources :pictures,      only: [:index, :show]

      resources :informations, only: [:index, :show] do
        member do
          patch :read
        end
      end

      resources :parking_units, only: [:show, :index]
      resources :storage_units, only: [:show, :index]

      resources :helpdesk_tickets, only: [:show, :index, :new, :create]
      # resources :suppliers TODO
    end
  end
end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar js-navbar navbar-wagon-fixed">

  <!-- Logo -->
  <div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-revive-white.svg" %>
    <% end %>
  </div>

  <!-- Middle Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <%= link_to t(".dashboard", default: '<i class="fa fa-home" aria-hidden="true"></i> Home'.html_safe ), customers_dashboard_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_dashboard}" %>

    <!-- Decisions -->
    <%= link_to t(".decisions", default: "Decisions"), customers_unit_decisions_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_decisions}" %>

    <!-- Site Visits -->
    <%= link_to t(".site visits", default: "Events"), customers_unit_site_visits_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_sitevisits}" %>

    <!-- Payments -->
    <%= link_to t(".payments", default: "Payments"), customers_unit_payments_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_payments}" %>

    <!-- Documents -->
    <%= link_to t(".documents", default: "Documents"), customers_unit_documents_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_documents}" %>


    <!-- News -->
    <%= link_to t(".news", default: "News"), customers_unit_news_index_path(@unit), class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_news}" %>
  </div>


  <!-- Profile picture and dropdown -->
  <div class="avatar-navbar-padding">

    <div class="navbar-wagon-right">



      <div class="dropdown dropdown-both-elements">

         <div class="name-navbar dropdown-toggle" id= "navbar-wagon-menu" data-toggle="dropdown">  <%= current_customer.first_name.capitalize %> </div>


          <%= cl_image_tag current_customer.picture, class: "avatar-navbar avatar-navbar-bordered", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">




        <li>
          <%= link_to customers_unit_helpdesk_tickets_path(@unit) do %>
            <i class="fa fa-question-circle-o"></i> <%= t(".questions", default: "My questions") %>
          <% end %>
        </li>

        <li>
          <%= link_to customers_profile_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Edit my profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_customer_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>

    </div>



</div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

    <div class="dropdown">

      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".dashboard", default: "Home"), customers_dashboard_path(@unit) %></li>
        <li><%= link_to t(".decisions", default: "Decisions"), customers_unit_decisions_path(@unit) %></li>
        <li><%= link_to t(".site visits", default: "Events"), customers_unit_site_visits_path(@unit) %></li>
        <li><%= link_to t(".payments", default: "Payments"), customers_unit_payments_path(@unit) %></li>
        <li><%= link_to t(".documents", default: "Documents"), customers_unit_documents_path(@unit) %></li>
        <li><%= link_to t(".news", default: "News"), customers_unit_news_index_path(@unit) %></li>

      </ul>
    </div>

  </div>

</div>

app/views/shared/_navbar_employee.html.erb
<div class="navbar-top-employees js-navbar navbar-wagon-fixed">

  <!-- Logo -->
  <div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-revive-white.svg" %>
    <% end %>
  </div>

  <!-- Middle Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to t(".dashboard", default: "Dashboard"), employees_dashboard_path, class: "navbar-wagon-item navbar-wagon-link #{"active" if @current_page_dashboard}" %>

  <% unless @project.nil? || @unit.nil? %>


  <!-- News -->
      <%= link_to t(".news", default: "News"), employees_project_news_index_path(@project, @phase), class: "navbar-wagon-item navbar-wagon-link" %>


  <!-- Decisions -->

      <!-- %= link_to t(".decisions", default: "Decisions"), employees_project_unit_decisions_path(@project, @unit), class: "navbar-wagon-item navbar-wagon-link" % -->



  <!-- Site Visits -->

      <!-- %= link_to t(".site visits", default: "Site Visits"), employees_project_unit_site_visits_path(@project, @unit), class: "navbar-wagon-item navbar-wagon-link" % -->



  <!-- Acceptance -->

      <!-- %= link_to t(".acceptance", default: "Handover"), employees_project_unit_handovers_path(@project, @unit), class: "navbar-wagon-item navbar-wagon-link" % -->



  <!-- Payments -->

      <!-- %= link_to t(".payments", default: "Payments"), employees_project_unit_payments_path(@project, @unit), class: "navbar-wagon-item navbar-wagon-link" % -->



  <!-- Documents -->

      <!-- %= link_to t(".documents", default: "Documents"), employees_project_unit_documents_path(@project, @unit), class: "navbar-wagon-item navbar-wagon-link" % -->
<% end %>



  </div>


  <!-- Profile picture and dropdown -->
  <div class="avatar-navbar-padding">

    <div class="dropdown">

        <%= cl_image_tag (current_employee.facebook_picture_url) , class: "avatar-navbar avatar-navbar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

 <!--        <li>
          <%#= link_to edit_customer_registration_path do %>
            <i class="fa fa-user"></i> <%#= t(".profile", default: "Profile") %>
          <%# end %>
        </li> -->
        <li>
          <%= link_to destroy_employee_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
        </ul>

    </div>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

    <div class="dropdown">

      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>

  </div>

</div>