config/routes.rb
Rails.application.routes.draw do
  root to: 'customers/dashboards#show'

#devise routes -----------------------------------------------------------------

  devise_for :customers,
    controllers: { invitations: "customers/invitations"}

  devise_for :employees,
    controllers: { omniauth_callbacks: "employees/omniauth_callbacks"}



#employee routes --------------------------------------------------------------

  namespace :employees do
    root to: 'dashboards#show'
    resource :dashboard, only: [:show]
    resources :helpdesk_tickets

    ## !! MFR 30-Aug-2016
    # routes added for consulting hours because it's related
    # to customer
    # /employees/customers/:customer_id/consulting_hours...
    resources :customers, only: [:index, :show] do |variable|
      resources :consulting_hours
    end
    ## !!

    # /projects (bla)
    # /projects/:id # listing the phases
    resources :projects, except: [:destroy] do
      # /projects/:project_id/phases/new + create
      # /projects/:project_id/phases/:id # listing lots
      resources :phases do
      end

      resources :news, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :lots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :buildings, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      end

      resources :storage_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :parking_units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        #resources :consulting_hours
        resources :documents
        resources :decisions
        resources :handovers
        resources :informations
        resources :site_visits
        resources :payments
        resources :pictures
      end
    end
  end

  #customer routes -------------------------------------------------------------

  namespace :customers do

    root to: 'customers/dashboards#show'
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update]

    resources :units, only: [:show, :index] do
      resource :dashboard,  only: [:show]

      resources :news,      only: [:index, :show]

      resources :decisions, only: [:index, :show] do
        member do
          patch :approve
          patch :reject
        end
      end

      resources :site_visits,   only: [:index, :show]
      resources :handovers,     only: [:index, :edit, :update] # for the remarks
      resources :payments,      only: [:index, :show]
      resources :documents,     only: [:index]
      resources :pictures,      only: [:index, :show]

      resources :informations, only: [:index, :show] do
        member do
          patch :read
        end
      end

      resources :parking_units, only: [:show, :index]
      resources :storage_units, only: [:show, :index]

      resources :helpdesk_tickets, only: [:show, :index, :new, :create]
      # resources :suppliers TODO
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :picture, PhotoUploader

  validates :first_name, :last_name, :address, :mobile_number, :email, :signing_date, presence: true
  validates :mobile_number, uniqueness: true
  validates :email, uniqueness: { case_sensitive: false }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :consulting_hours, dependent: :destroy
  has_many :employees, through: :consulting_hours

  # beware here : although a customer has units,
  # destroying a customer should not destroy the
  # units he's bought. units.customer_id should be
  # set to nil
  has_many :units, dependent: :nullify


end

app/controllers/customers/base_controller.rb
class Customers::BaseController < ApplicationController
  before_action :set_unit, if: :customer_signed_in?
  before_action :authenticate_customer!
  layout "customer"

  private

  def set_unit
    if params[:unit_id]
      @unit = current_customer.units.find(params[:unit_id])
    else
      @unit = current_customer.units.first
    end
  end
end

app/controllers/customers/dashboards_controller.rb
class Customers::DashboardsController < Customers::BaseController
  def show
    @unit = current_customer.units.first
    @units = current_customer.units
    @news = @unit.building.lot.phase.news.last(5)

    @informations = @unit.information.all

    @timeline = @unit.payments.sort_by(&:id)
    @webcams = @unit.building.lot.phase.project.webcams
    @project = @unit.building.lot.phase.project

    # CONSULTING HOURS WIDGET
    @consultinghours = ConsultingHour.where(customer_id: current_customer)
    @max_consulting = @unit.consulting_hours
    @elapsedhours = calculate_hours(@consultinghours)

    # IMPORTANT WIDGET
    @events = combine_events

    @employee_id = @project.employee_projects.first.employee_id
    @employee = Employee.find(@employee_id)
    @current_page_dashboard = true
  end

private

  def calculate_hours(consultinghours)
    elapsedhours = 0
    consultinghours.each do |consultation|
        elapsedhours += consultation.elapsed_time
      end
    return elapsedhours
  end

  def combine_events
    events = []
    events << @unit.payments.where(status: "pending")
    events << @unit.site_visits
    events << @unit.handovers
    events << @unit.decisions.where(status: "pending")
    return events
  end
end

app/controllers/customers/decisions_controller.rb
class Customers::DecisionsController < Customers::BaseController

  def index #-------------------------------------------------------
    # list Decisions pertaining to the current unit
    unit_id = params[:unit_id]
    @decisions = Decision.where(unit_id:unit_id)
    @unit = Unit.find(unit_id)
    @current_page_decisions = true
  end

  def show # -------------------------------------------------------
    @decision = Decision.find(params[:id])
    @supplier = Supplier.find(@decision.supplier_id)
    @unit = Unit.find(@decision.unit_id)
    @document = Document.find(@decision.document_id)
    respond_to do |format|
      format.html { redirect_to customers_unit_decision_path(@unit, @decision) }
      format.js
    end
  end

  def approve # ----------------------------------------------------
    @decision = Decision.find(params[:id])
    if @decision.status.downcase == "pending"
      @decision.status = "approved"
      if @decision.update(params_decision)
        flash[:notice] = 'Decision approved'
        redirect_back(fallback_location: root_path) and return
      else
        flash[:alert] = 'Error saving'
        redirect_back(fallback_location: root_path) and return
      end
    else
      flash[:alert] = "Decision is already set (" + @decision.status.downcase + ")"
      redirect_back(fallback_location: root_path) and return
    end
  end

  def reject # -------------------------------------------------------
    @decision = Decision.find(params[:id])
    if @decision.status.downcase == "pending"
      @decision.status = "rejected"
      if @decision.update(params_decision)
        flash[:notice] = 'Decision rejected'
        redirect_back(fallback_location: root_path) and return
      else
        flash[:alert] = 'Error saving'
        redirect_back(fallback_location: root_path) and return
      end
    else
      flash[:alert] = "Decision is already set (" + @decision.status.downcase + ")"
      redirect_back(fallback_location: root_path) and return
    end
  end


private ##################################################################

  def params_decision
    params.fetch(:decision, {}).permit(:unit_id, :supplier_id, :document_id,
                                     :title, :description, :date, :due_date,
                                     :status)
  end

end

app/controllers/customers/documents_controller.rb
class Customers::DocumentsController < Customers::BaseController
  def index
    @documents = Document.all
    @kindU = kind_unique(@documents)
    @current_page_documents = true
  end

  def show
  end

  private


  def kind_unique(documents)
    @documents.select(:kind).map(&:kind).uniq
  end
end

app/controllers/customers/handovers_controller.rb
class Customers::HandoversController < Customers::BaseController
  def index #------------------------------------------------------
    # displays only handovers pertaining to the current unit
    unit_id = @unit.id
    @handovers = Handover.where(unit_id:unit_id)
    unless @handovers.nil? || @handovers.empty?
      if @handovers.length > 2
        flash[:alert] = "There can only be two handovers."
      end
    end
  end

  def edit #-------------------------------------------------------
    @handover = Handover.find(params[:id])
    respond_to do |format|
      format.html { redirect_to edit_customers_unit_handover_path(@unit, @handover) }
      format.js
    end
  end

  def update #-----------------------------------------------------
    @handover = Handover.find(params[:id])
    if @handover.update(params_handover)
      flash[:notice] = 'Remarks Saved'
      redirect_to customers_unit_site_visits_path and return
    else
      flash[:alert] = 'Error saving'
      redirect_back(fallback_location: root_path) and return
    end
  end

private ##################################################################

  def params_handover
    params.fetch(:handover, {}).permit(:unit_id, :title, :description,
                                       :date, :customer_remarks,
                                       :employee_remarks, :document_id)
  end

end

app/controllers/customers/helpdesk_tickets_controller.rb
class Customers::HelpdeskTicketsController < Customers::BaseController

  def index#--------------------------------------------------------
    unit_id = params[:unit_id]
    @tickets = HelpdeskTicket.where(unit_id:unit_id)
  end

  def show #--------------------------------------------------------
    @ticket = HelpdeskTicket.find(params[:id])
    @unit = Unit.find(@ticket.unit_id)
    respond_to do |format|
      format.html { redirect_to customers_unit_helpdesk_ticket_path(@unit, @ticket) }
      format.js
    end

  end


  def new #--------------------------------------------------------
    @helpdesk_ticket = HelpdeskTicket.new

    respond_to do |format|
      format.html { redirect_to new_customers_unit_helpdesk_ticket_path(@unit, @helpdesk_ticket) }
      format.js
    end
  end


  def create #--------------------------------------------------------
    @helpdesk_ticket = HelpdeskTicket.new(params_helpdesk_ticket)
    @helpdesk_ticket.unit_id = @unit.id
    @helpdesk_ticket.answers = ""
    project_id = @unit.building.lot.phase.project.id
    @employee_project = EmployeeProject.find_by(project_id:project_id)
    @helpdesk_ticket.employee_id = @employee_project.employee_id
    if @helpdesk_ticket.save!
      redirect_to customers_unit_helpdesk_tickets_path(@unit) and return
    else
      render :new
    end
  end

private

  def params_helpdesk_ticket
    params.fetch(:helpdesk_ticket, {}).permit(:title, :description)
  end


end

app/controllers/customers/informations_controller.rb
class Customers::InformationsController < Customers::BaseController
  # /customers/units/:unit_id/informations(.:format)
  def index
    @informations = @unit.informations
  end

  # /customers/units/:unit_id/informations/:id(.:format)
  def show
    @information = Information.find(params[:id])
    unless @information.document_id.nil?
      @document = Document.find(@information.document_id)
    end
    respond_to do |format|
      format.html { redirect_to customers_unit_information_path(@unit, @information) }
      format.js
    end
  end

  def read
    @information = Information.find(params[:id])
    @information.update!(read: true)
    redirect_to root_path
  end

end

app/controllers/customers/invitations_controller.rb
class Customers::InvitationsController < Devise::InvitationsController
  before_action :disable_creation, only: [:new, :create]

  private

  def disable_creation
    flash[:alert] = "Nice try [418]"
    redirect_to root_path
  end
end

app/controllers/customers/news_controller.rb
class Customers::NewsController < Customers::BaseController
  def index
    @news = @unit.building.lot.phase.news.order(date: :desc)
    @current_page_news = true
  end

  def show
    @news = News.find(params[:id])
    respond_to do |format|
      format.html { redirect_to customers_unit_news_path(@unit, @news) }
      format.js
    end
  end
end

app/controllers/customers/parking_units_controller.rb
class Customers::ParkingUnitsController < Customers::BaseController
  def index
  end

  def show
  end
end

app/controllers/customers/payments_controller.rb
class Customers::PaymentsController < Customers::BaseController
  def index
    @payments = current_customer.units.first.payments
    @pending = pending(@payments)
    @completed = completed(@payments)
    @future_payments = future_payments(@payments)
    @current_page_payments = true
  end

  def show
  end

  private

#method for calculating total pending-------------------------------------------
   def pending(payments)
    pending = 0
    payments.each do |payment|
      if payment.status == "pending"
      pending += payment.amount
      end
    end
    return pending
  end

#method for calculating total completed-----------------------------------------

    def completed(payments)
    completed = 0
    payments.each do |payment|
      if payment.status == "completed"
      completed += payment.amount
      end
    end
    return completed
  end

#method for calculating total future_payments-----------------------------------------
#
    def future_payments(payments)
    future_payments = 0
    payments.each do |payment|
      if payment.status == "future payment"
      future_payments += payment.amount
      end
    end
    return future_payments
  end

end

app/controllers/customers/pictures_controller.rb
class Customers::PicturesController < Customers::BaseController
  def index
      unit_id = params[:unit_id]
      @pictures = Picture.where(unit_id: unit_id)
  end

  def show
  end

end

app/controllers/customers/profiles_controller.rb
class Customers::ProfilesController < Customers::BaseController

  def show
    @user = current_customer
  end

  def edit
    @user = current_customer
  end

  def update
    @user = current_customer
    @user.update(params.require(:customer).permit(:email, :password, :password_confirmation, :phone_number, :mobile_number, :address))
    redirect_to customers_dashboard_path
  end


end

app/controllers/customers/site_visits_controller.rb
class Customers::SiteVisitsController < Customers::BaseController
  def index
    unit_id = @unit.id
    @sitevisits = SiteVisit.where(unit_id: unit_id)
    @project = @unit.building.lot.phase.project
    @current_page_sitevisits = true

    @hash = Gmaps4rails.build_markers(@project) do |project, marker|
      marker.lat project.latitude
      marker.lng project.longitude
    end

    unit_id = @unit.id
    @handovers = Handover.where(unit_id:unit_id)
    unless @handovers.nil? || @handovers.empty?
      if @handovers.length > 2
        flash[:alert] = "There can only be two handovers."
      end
    end

    @longitude_project = @project.longitude
    @latitude_project = @project.latitude

    @unit

    @longitude_customer = @unit.customer.longitude
    @latitude_customer = @unit.customer.latitude
  end



private ##################################################################

  def params_handover
    params.fetch(:handover, {}).permit(:unit_id, :title, :description,
                                       :date, :customer_remarks,
                                       :employee_remarks, :document_id)
  end
end

app/controllers/customers/storage_units_controller.rb
class Customers::StorageUnitsController < Customers::BaseController
  def index
  end

  def show
  end
end

app/controllers/customers/units_controller.rb
class Customers::UnitsController < Customers::BaseController
  def index
  end

  def show
  end
end

app/controllers/employees/customers_controller.rb
class Employees::CustomersController< Employees::BaseController

  def index
    @customers = Customer.all.order(last_name: :asc)
  end

  def show
    @customer = Customer.find(params[:id])
    @units = Unit.where("customer_id = " + params[:id])
  end

end

app/controllers/employees/dashboards_controller.rb
class Employees::DashboardsController < Employees::BaseController
  def show
    @employee_projects = current_employee.projects


  end
end

app/views/customers/dashboards/show.html.erb
<% content_for :title, "Home" %>

<div class="container">

  <div class="distance">
    <div class="container-small-customer-dashboard">
      <!-- First Row -->

      <div class="row">
        <!-- Timeline col -->
        <div class="col-sm-8">
         <p class="line large"></p>
         <div class="well">

          <p class="list-group-item"><i class="fa fa-calendar padd-icon" aria-hidden="true"></i><strong> TIMELINE</strong></p>
          <div class="progress-bar-custom">
            <div class="dot dot-active" data-toggle="tooltip" title="Start of project!"></div>
            <% @timeline.each do  |item| %>

            <!-- Generated markup by the plugin -->
            <div class="tooltip bottom" role="tooltip">
              <div class="tooltip-arrow"></div>
              <div class="tooltip-inner">

              </div>
            </div>

            <% if item.status == "future payment" %>
            <div class="bar"></div>
            <div class="dot" data-toggle="tooltip" title="<%= item.description %>"></div>
            <% else %>
            <div class="bar bar-active"></div>
            <div class="dot dot-active" data-toggle="tooltip" title="<%= item.description %>"></div>
            <% end %>
            <% end %>
          </div>

        </div>
      </div>

      <div class="col-sm-4">
        <div class="panel panel-default" style="height: 258px;">
          <p class="line middle"></p>
          <p class="list-group-item"><strong> ABOUT</strong></p>
          <div class="panel-body text-center" style="height: 50px;"">
            <p><strong>Name: </strong><%= @unit.unit_name %>   <strong>    Project: </strong><%= @project.commercial_name %></p>
          </div>
          <ul class="list-group">

            <li class="list-group-item"><i class="fa fa-user padd-icon" aria-hidden="true"></i></i> Project Manager: <%= @employee.first_name%> <%= @employee.last_name %></li>
            <li class="list-group-item"><i class="fa fa-phone padd-icon" aria-hidden="true"></i> <%= @employee.mobile_number %></li>
            <li class="list-group-item"><i class="fa fa-envelope padd-icon" aria-hidden="true"></i> <%= @employee.email %></li>
            <li class="list-group-item last-fucking-item last-color about-last-item"><i class="fa fa-camera padd-icon" aria-hidden="true"></i> <%= link_to 'Pictures', customers_unit_pictures_path(@unit)%></li>

          </ul>
        </div>
      </div>


    </div>
    <!-- END Timeline col -->
    <!-- END First Row -->

    <!-- Second Row -->
    <div class="row">

      <!-- Webcam col -->


      <div class="col-xs-12 col-sm-4">

       <div class="list-group">
        <p class="line top"></p>
        <p class="list-group-item"><i class="fa fa-exclamation padd-icon" aria-hidden="true"></i><strong> IMPORTANT</strong></p>
        <div class="scrollable-panel">
          <% @events.each do |objects| %>
            <% objects.each do |object| %>
              <a href="#" class="list-group-item padding-item"><%= object.title %></a>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8">

      <div class="well card-carousel" style="background-size: cover;">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="<%= prev_num = 0 %>" class="active"></li>
            <% (@webcams.size-1).times do %>
            <li data-target="#carousel-example-generic" data-slide-to="<%= prev_num += 1 %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <div class="item active img-responsive"><img src="<%= @webcams.first.url %>"></div>
            <% @webcams.drop(1).each do |webcam| %>
            <div class="item img-responsive"><img src="<%= webcam.url %>"></div>
            <% end %>
          </div>
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
      </div>
    </div>

    <!-- Important info col -->

  </div>






  <!-- Third row -->
  <div class="third-row-padding">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="list-group">
          <p class="line left"></p>
          <p class="list-group-item"><i class="fa fa-clock-o padd-icon" aria-hidden="true"></i><strong> CONSULTING HOURS</strong><span class="badge badge-hours text-right"> <%= @max_consulting - @elapsedhours %> out of <%= @max_consulting %> hours left</span></p>
          <% @consultinghours.each do |consultation| %>
            <a class="list-group-item padding-item"><%= consultation.description %> <span class="badge badge-hours text-right"><%= consultation.elapsed_time%>h</span></a>
          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="list-group">
          <p class="line middle"></p>
          <p class="list-group-item"><i class="fa fa-newspaper-o padd-icon" aria-hidden="true"></i><strong> NEWS</strong></p>
          <% @news.each do |news_item| %>
            <%= link_to  customers_unit_news_path(@unit, news_item), class: "list-group-item padding-item", remote: true do %>
              <%= news_item.title %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="list-group">
          <p class="line right"></p>
          <p class="list-group-item"><i class="fa fa-info padd-icon" aria-hidden="true"></i><strong> INFORMATION</strong></p>
          <% @informations.each do |information| %>
            <%= link_to  customers_unit_information_path(@unit, information), class: "list-group-item padding-item", remote: true do %>
              <%= information.title %>
              <% if information.read %>
                <span class="badge badge-information text-right">accepted</span>
              <% else %>
                <span class="badge badge-information text-right">unread</span>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
  <!-- END Third row -->



</div>



</div>

</div>


<!-- Modal Information check-->
<div class="modal fade" id="informationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>


<!-- Modal News check-->
<div class="modal fade" id="newsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>